// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: backend/proto/notification/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendConfirmationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      string                 `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendConfirmationRequest) Reset() {
	*x = SendConfirmationRequest{}
	mi := &file_backend_proto_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendConfirmationRequest) ProtoMessage() {}

func (x *SendConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendConfirmationRequest.ProtoReflect.Descriptor instead.
func (*SendConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendConfirmationRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *SendConfirmationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type SendConfirmationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendConfirmationResponse) Reset() {
	*x = SendConfirmationResponse{}
	mi := &file_backend_proto_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendConfirmationResponse) ProtoMessage() {}

func (x *SendConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendConfirmationResponse.ProtoReflect.Descriptor instead.
func (*SendConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendConfirmationResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

func (x *SendConfirmationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_backend_proto_notification_notification_proto protoreflect.FileDescriptor

const file_backend_proto_notification_notification_proto_rawDesc = "" +
	"\n" +
	"-backend/proto/notification/notification.proto\x12\fnotification\"P\n" +
	"\x17SendConfirmationRequest\x12\x1a\n" +
	"\bcustomer\x18\x01 \x01(\tR\bcustomer\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"H\n" +
	"\x18SendConfirmationResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2x\n" +
	"\x13NotificationService\x12a\n" +
	"\x10SendConfirmation\x12%.notification.SendConfirmationRequest\x1a&.notification.SendConfirmationResponseB*Z(shared/proto/notification;notificationpbb\x06proto3"

var (
	file_backend_proto_notification_notification_proto_rawDescOnce sync.Once
	file_backend_proto_notification_notification_proto_rawDescData []byte
)

func file_backend_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_backend_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_backend_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_notification_notification_proto_rawDesc), len(file_backend_proto_notification_notification_proto_rawDesc)))
	})
	return file_backend_proto_notification_notification_proto_rawDescData
}

var file_backend_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backend_proto_notification_notification_proto_goTypes = []any{
	(*SendConfirmationRequest)(nil),  // 0: notification.SendConfirmationRequest
	(*SendConfirmationResponse)(nil), // 1: notification.SendConfirmationResponse
}
var file_backend_proto_notification_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationService.SendConfirmation:input_type -> notification.SendConfirmationRequest
	1, // 1: notification.NotificationService.SendConfirmation:output_type -> notification.SendConfirmationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_proto_notification_notification_proto_init() }
func file_backend_proto_notification_notification_proto_init() {
	if File_backend_proto_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_notification_notification_proto_rawDesc), len(file_backend_proto_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_backend_proto_notification_notification_proto_depIdxs,
		MessageInfos:      file_backend_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_backend_proto_notification_notification_proto = out.File
	file_backend_proto_notification_notification_proto_goTypes = nil
	file_backend_proto_notification_notification_proto_depIdxs = nil
}
