// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: backend/proto/order/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      string                 `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_backend_proto_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *PlaceOrderRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *PlaceOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_backend_proto_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_backend_proto_order_order_proto protoreflect.FileDescriptor

const file_backend_proto_order_order_proto_rawDesc = "" +
	"\n" +
	"\x1fbackend/proto/order/order.proto\x12\x05order\"_\n" +
	"\x11PlaceOrderRequest\x12\x1a\n" +
	"\bcustomer\x18\x01 \x01(\tR\bcustomer\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"G\n" +
	"\x12PlaceOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2Q\n" +
	"\fOrderService\x12A\n" +
	"\n" +
	"PlaceOrder\x12\x18.order.PlaceOrderRequest\x1a\x19.order.PlaceOrderResponseB\x1cZ\x1ashared/proto/order;orderpbb\x06proto3"

var (
	file_backend_proto_order_order_proto_rawDescOnce sync.Once
	file_backend_proto_order_order_proto_rawDescData []byte
)

func file_backend_proto_order_order_proto_rawDescGZIP() []byte {
	file_backend_proto_order_order_proto_rawDescOnce.Do(func() {
		file_backend_proto_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_order_order_proto_rawDesc), len(file_backend_proto_order_order_proto_rawDesc)))
	})
	return file_backend_proto_order_order_proto_rawDescData
}

var file_backend_proto_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backend_proto_order_order_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil),  // 0: order.PlaceOrderRequest
	(*PlaceOrderResponse)(nil), // 1: order.PlaceOrderResponse
}
var file_backend_proto_order_order_proto_depIdxs = []int32{
	0, // 0: order.OrderService.PlaceOrder:input_type -> order.PlaceOrderRequest
	1, // 1: order.OrderService.PlaceOrder:output_type -> order.PlaceOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_proto_order_order_proto_init() }
func file_backend_proto_order_order_proto_init() {
	if File_backend_proto_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_order_order_proto_rawDesc), len(file_backend_proto_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_order_order_proto_goTypes,
		DependencyIndexes: file_backend_proto_order_order_proto_depIdxs,
		MessageInfos:      file_backend_proto_order_order_proto_msgTypes,
	}.Build()
	File_backend_proto_order_order_proto = out.File
	file_backend_proto_order_order_proto_goTypes = nil
	file_backend_proto_order_order_proto_depIdxs = nil
}
